pipeline:
  build:
    image: cboettig/labnotebook:3.4.2
    commands:
      - R -e 'devtools::install(dep=TRUE)'
      - R -e 'lapply(list.files("code", pattern="*.R$", full.names = TRUE, recursive=TRUE), source)'
      - R -e 'lapply(list.files(pattern=".*.Rmd", recursive=TRUE), rmarkdown::render)'

